name: 'End SonarScanner Dotnet'
description: 'Runs sonar scan for DotNet'
inputs:
  sonar-token:
    description: 'Sonar Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: End SonarQube
      run: |
        export PATH="$PATH:/github/home/.dotnet/tools:/root/.dotnet/tools"
        dotnet-sonarscanner end /d:sonar.login="${{ inputs.sonar-token }}"
      shell: bash