name: CI

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'
      - 'release/**'
      - 'rc/**'
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'dev'

jobs:

  build:
    name: Build, Test & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -t sonardemo --build-arg DOCKER_TAG=sonardemo --build-arg SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} -f ./SonarPlaygroundGBActions/Dockerfile --progress=plain ./SonarPlaygroundGBActions/.
        shell: bash
